name: Docker Build

inputs:
  server-ip:
    description: 'Server IP address'
    required: true
  server-ssh-port:
    description: 'Server SSH port'
    required: true
  server-ssh-secret-key:
    description: 'The SSH secret key from server'
    required: true
  server-ssh-user:
    description: 'SSH User'
    required: true

runs:
  using: "composite"
  steps:
    - name: Write secret to file
      working-directory: src
      run: echo "${{ inputs.server-ssh-secret-key }}" > priv.key
      shell: bash

    - name: Git Pull
      working-directory: src
      run: ../composite-actions/helpers/ssh-docker-compose/git-pul.sh ${{ inputs.server-ip }} ${{ inputs.server-ssh-port }} ${{ inputs.server-ssh-user }}
      shell: bash

    - name: Rebuild and up the Docker Compose
      working-directory: src
      run: ../composite-actions/helpers/ssh-docker-compose/rebuild-and-up.sh ${{ inputs.server-ip }} ${{ inputs.server-ssh-port }} ${{ inputs.server-ssh-user }}
      shell: bash