name: Node Operation

inputs:
  node-version:
    description: 'Node version'
    required: true
  node-command:
    description: 'Node command that will be executed'
    required: true

runs:
  using: "composite"
  steps:
    - name: Node Command Execution
      run: ./composite-actions/helpers/node/node-operation.sh ${{ inputs.node-version }} "${{ inputs.node-command }}"
      shell: bash

