name: Rollout

inputs:
  app-name:
    description: 'Application Name'
    required: true
  service-name:
    description: 'Service Name'
    required: true
  cluster-name:
    description: 'Cluster Name'
    required: true


runs:
  using: "composite"
  steps:

    - name: Install gcloud-auth-plugin
      run: |
        REPO_URL="https://packages.cloud.google.com/apt"
        # Install the Google Cloud SDK
        echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] $REPO_URL cloud-sdk main" | sudo tee /etc/apt/sources.list.d/google-cloud-sdk.list
        sudo curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key --keyring /usr/share/keyrings/cloud.google.gpg add -
        sudo apt-get update -y
        sudo apt-get install -y google-cloud-sdk-gke-gcloud-auth-plugin
      shell: bash

    - name: Write secret to file
      run: echo "${{ secrets.GCLOUD_SERVICE_ACCOUNT }}" | base64 --decode > gcp.json
      shell: bash

    - name: Rollout
      run: ./composite-actions/helpers/general/rollout.sh  ${{ inputs.app-name }} ${{ inputs.service-name }}  $GITHUB_REF_NAME.$GITHUB_SHA ${{ inputs.cluster-name }}
      shell: bash
